/**
 * EACH MODULE WITH CONTROLLER MUST BE REGISTERED HERE IF WE ARE GOING TO USE THE @HasPermissionDecorator IN OUR ROUTES
 */
export enum ROUTE_RESOURCE {
  USERS = 'USERS',
  ROLES = 'ROLES',
  PERMISSIONS = 'PERMISSIONS'
}